name: Build Image

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: registry.bodysoft.com.br/autobot/server
  REGISTRY: registry.bodysoft.com.br

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Trigger Deploy Workflow
        uses: peter-evans/workflow-dispatch@v2
        with:
          workflow: "deploy.yaml"
          ref: main