name: Deploy via ArgoCD

on:
  push:
    branches: [ main ]

env:
  APP_NAME: autobot
  ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
  ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
  IMAGE_NAME: registry.bodysoft.com.br/autobot/server
  REGISTRY: registry.bodysoft.com.br

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ vars.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: [build]
    steps:
      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd

      - name: Sync app via ArgoCD
        run: |
          argocd app create $APP_NAME \
            --dest-namespace $APP_NAME \
            --dest-server https://kubernetes.default.svc \
            --helm-set image.tag=${{ github.sha }} \
            --helm-set secret.DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} \
            --project default \
            --revision 0.1.0 \
            --server ${{ env.ARGOCD_SERVER }} \
            --upsert --grpc-web \
            --auth-token ${{ env.ARGOCD_TOKEN }} \
            --sync-option CreateNamespace=true \
            --values-literal-file helm/values.yaml

          argocd app sync $APP_NAME \
            --server ${{ env.ARGOCD_SERVER }} \
            --force \
            --retry-limit 3 \
            --grpc-web \
            --auth-token ${{ env.ARGOCD_TOKEN }} \
            --timeout 2100
